env:
  matrix:
    - ANDROID_SDKS=android-15,sysimg-15  ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a  CMD=unit_test.sh
    - ANDROID_SDKS=android-15,sysimg-15  ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a  CMD=emulator_test.sh

language: android
android:
  components:
    - build-tools-19.0.2
    - android-8
  licenses:
    - 'android-sdk-.*'
    - '.*intel.+'
script:
  - sh RapidFTR-Android/travis/$CMD
notifications:
  - email: false
